### ISSUE TITLE
Issue with Paper 1.19.3+ chunk system rewrite

### ISSUE THREAD

**Issue by Boy0000** [IPECTER/LighterAPI#2]
One of the original issues with LightAPI still persists here
Tried looking into this myself but could not figure it out
Essentially the issue was just that Starlight removed a parameter. Not sure what the required change is
But Light(er)API is essentially broken on all Paper 1.19.3+ builds atm
```
[12:11:14 WARN]: java.lang.RuntimeException: (NoSuchFieldException) e
[12:11:14 WARN]:        at LightAPI-Bukkit-5.4.0-SNAPSHOT.jar//ru.beykerykt.minecraft.lightapi.bukkit.internal.handler.craftbukkit.nms.BaseNMSHandler.toRuntimeException(BaseNMSHandler.java:40)
[12:11:14 WARN]:        at LightAPI-Bukkit-5.4.0-SNAPSHOT.jar//ru.beykerykt.minecraft.lightapi.bukkit.internal.handler.craftbukkit.nms.v1_19_R1.VanillaNMSHandler.onInitialization(VanillaNMSHandler.java:180)
[12:11:14 WARN]:        at LightAPI-Bukkit-5.4.0-SNAPSHOT.jar//ru.beykerykt.minecraft.lightapi.bukkit.internal.handler.craftbukkit.nms.v1_19_R1.StarlightNMSHandler.onInitialization(StarlightNMSHandler.java:231)
[12:11:14 WARN]:        at LightAPI-Bukkit-5.4.0-SNAPSHOT.jar//ru.beykerykt.minecraft.lightapi.bukkit.internal.BukkitPlatformImpl.initialization(BukkitPlatformImpl.java:229)
[12:11:14 WARN]:        at LightAPI-Bukkit-5.4.0-SNAPSHOT.jar//ru.beykerykt.minecraft.lightapi.common.LightAPI.initialization(LightAPI.java:88)
[12:11:14 WARN]:        at LightAPI-Bukkit-5.4.0-SNAPSHOT.jar//ru.beykerykt.minecraft.lightapi.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:70)
```

**Comment by IPECTER** [comment]
can you join discord?
https://discord.gg/WnC2wFa6Uq

**Comment by IPECTER** [comment]
1. remove LightAPI folder
2. start server
3. stop server
4. set config debug to true
5. start server
6. send full log to here

**Comment by Boy0000** [comment]
nvm i must have had something wrong sorry... seems to work just fine
